name: Build binary artifacts

on:
  push:
    tags:
      - "v*"

jobs:
  binaries:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] # windows-latest,

    runs-on: ${{ matrix.os }}

    permissions:
      # NOTE: Needed to save artifacts the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools pyinstaller
          pip install .
      - name: Build the binary
        run: |
          make -C bindist
          cd bindist && echo "DIST_FILE=`make dist-name | tr -d '\n'`" >> $GITHUB_ENV
      - name: Release binary artifacts
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: bindist/${{ env.DIST_FILE }}
